### ISSUE TITLE
status": 403,     "error": {         "message": "Restricted."

### ISSUE THREAD

**Issue by tonymossfield** [apisentris/public-issue#1]
I am using GET to https://apisentris.com/api/v1/authors/

using content type, client id, and access toen, but get:

{
    "status": 403,
    "error": {
        "message": "Restricted."
    }
}

**Comment by absyah** [comment]
Hi @tonymossfield thanks for reporting this.
Let me check on my end

**Comment by absyah** [comment]
Hi @tonymossfield could you please make sure your request body is filled with all required data?
Possibly there is NOT NULL role in the columns but you left it blank in the json req body.

**Comment by absyah** [comment]
oh sorry... GET request does not need request body

**Comment by absyah** [comment]
@tonymossfield You can remove whitelisted access from your Apisentris' connection since it blocks every network coming from outside that whitelisted domain. It supposes to be filled with your production domains. If it does work please let me know so I can close this issue :+1: 

Just for note, if you fill the whitelisted label you won't be able to make a request from your local machine as well. So better to remove whitelisted if it is for development purposes.

**Comment by tonymossfield** [comment]
Hi Ardian,
Whitelisting was the issue and it is now working.
Thanks for your help.
Regards
Tony
    On Thursday, 20 February 2020, 06:13:29 pm AEDT, Ardian Bahtiarsyah <notifications@github.com> wrote:  
 
 
@tonymossfield You can remove whitelisted access from your Apisentris' connection since it blocks every network coming from outside that whitelisted domain. It supposes to be filled with your production domains. If it does work please let me know so I can close this issue 👍
 
Just for note, if you fill the whitelisted label you won't be able to make a request from your local machine as well. So better to remove whitelisted if it is for development purposes.

**Comment by absyah** [comment]
Thanks @tonymossfield 
I'm closing this. Please let me know whenever you got another issue. Have a good day
